### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by joenilan** [Groestlcoin/groestltip-streamlabs#4]
What is the flow the site takes? Present such images/idea here.

**Comment by 0xViva** [comment]
## Homepage
![image](https://user-images.githubusercontent.com/16744145/33844426-92ff9df8-dea0-11e7-9a75-dc5a0e53058d.png)
## User page
![image](https://user-images.githubusercontent.com/16744145/33844852-e8fb3bb2-dea1-11e7-9699-f236adb13b22.png)
## User settings
![image](https://user-images.githubusercontent.com/16744145/33844942-2471f3ac-dea2-11e7-87f5-b575c154a97c.png)
